default:
  tags:
    - Fulen

# build-job:
#   stage: build
#   image:
#     name: rust:1.69.0-bullseye
#   script:
#     - echo "Hello, $GITLAB_USER_LOGIN!"
#     - echo "I am $(whoami)"
#     - cargo build

cargo-clippy:
  stage: test
  image:
    name: rust:1.69.0-bullseye
  script:
    - rustup update 
    - rustup component add clippy-preview
    - cargo clippy

cargo-audit:
  stage: test
  image:
    name: rust:1.69.0-bullseye
  script:
    - cargo install cargo-audit
    - cargo audit

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
