default:
  tags:
    - Fulen

build-job:
  stage: build
  image:
    name: rust:1.69.0-bullseye
  script:
    - rustup component add rustfmt
    - cargo fmt
    - cargo build

cargo-clippy-audit:
  stage: test
  image:
    name: rust:1.69.0-bullseye
  script:
    - rustup update 
    - rustup component add clippy-preview
    - cargo clippy
    - cargo install cargo-audit
    - cargo audit --ignore RUSTSEC-2020-0071

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
