.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-get-cluster 1  "cluster " 
.SH NAME
manta\-get\-cluster \- Show cluster node details and status
.SH SYNOPSIS
\fBmanta get cluster\fR [\fB\-n\fR|\fB\-\-nids\-only\-one\-line\fR] [\fB\-x\fR|\fB\-\-xnames\-only\-one\-line\fR] [\fB\-s\fR|\fB\-\-status\fR] [\fB\-T\fR|\fB\-\-summary\-status\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fICLUSTER_NAME\fR> 
.SH DESCRIPTION
Show cluster node details and status
.SH OPTIONS
.TP
\fB\-n\fR, \fB\-\-nids\-only\-one\-line\fR
Print NIDs on a single line
.TP
\fB\-x\fR, \fB\-\-xnames\-only\-one\-line\fR
Print xnames on a single line
.TP
\fB\-s\fR, \fB\-\-status\fR \fI<VALUE>\fR
Filter nodes by status
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
OFF
.IP \(bu 2
ON
.IP \(bu 2
READY
.IP \(bu 2
STANDBY
.IP \(bu 2
PENDING
.IP \(bu 2
FAILED
.IP \(bu 2
CONFIGURED
.RE
.TP
\fB\-T\fR, \fB\-\-summary\-status\fR
Show a cluster status summary:
OK          — all nodes booted and configured
OFF         — at least one node is OFF
ON          — no nodes OFF, at least one is ON
STANDBY     — at least one node\*(Aqs heartbeat is lost
UNCONFIGURED — all nodes READY but at least one is still being configured
FAILED      — at least one node\*(Aqs configuration failed
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<FORMAT>\fR [default: table]
Output format
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
table
.IP \(bu 2
table\-wide
.IP \(bu 2
json
.IP \(bu 2
summary
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fICLUSTER_NAME\fR>
Cluster name
