.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-run 1  "run " 
.SH NAME
manta\-run \- Create and run a configuration session from a local Ansible repo
.SH SYNOPSIS
\fBmanta run\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Create and run a configuration session from a local Ansible repo
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
manta\-run\-session(1)
Create and run a configuration session from a local repo
