.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-cli-power-reset-cluster 1  "cluster " 
.SH NAME
manta\-cli\-power\-reset\-cluster \- Reset all nodes in a cluster
.SH SYNOPSIS
\fBmanta\-cli power reset cluster\fR [\fB\-g\fR|\fB\-\-graceful\fR] [\fB\-y\fR|\fB\-\-assume\-yes\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-r\fR|\fB\-\-reason\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fICLUSTER_NAME\fR> 
.SH DESCRIPTION
Reset all nodes in a cluster
.SH OPTIONS
.TP
\fB\-g\fR, \fB\-\-graceful\fR
Perform a graceful reboot
.TP
\fB\-y\fR, \fB\-\-assume\-yes\fR
Skip confirmation prompts
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<FORMAT>\fR [default: table]
Output format
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
table
.IP \(bu 2
json
.RE
.TP
\fB\-r\fR, \fB\-\-reason\fR \fI<TEXT>\fR
Reason for the power operation
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fICLUSTER_NAME\fR>
Cluster name
