.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-config-show 1  "show " 
.SH NAME
manta\-config\-show \- Show current configuration values
.SH SYNOPSIS
\fBmanta config show\fR [\fB\-o\fR|\fB\-\-output\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show current configuration values
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<FORMAT>\fR [default: table]
Output format
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
table
.IP \(bu 2
json
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
