.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-cli-serve 1  "serve " 
.SH NAME
manta\-cli\-serve \- Run manta as an HTTP/HTTPS API server
.SH SYNOPSIS
\fBmanta\-cli serve\fR [\fB\-\-port\fR] [\fB\-\-cert\fR] [\fB\-\-key\fR] [\fB\-\-listen\-address\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Run manta as an HTTP/HTTPS API server
.SH OPTIONS
.TP
\fB\-\-port\fR \fI<PORT>\fR [default: 8080]
Port to listen on
.TP
\fB\-\-cert\fR \fI<CERT_FILE>\fR
Path to TLS certificate PEM file (enables HTTPS)
.TP
\fB\-\-key\fR \fI<KEY_FILE>\fR
Path to TLS private key PEM file (required with \-\-cert)
.TP
\fB\-\-listen\-address\fR \fI<ADDRESS>\fR [default: 0.0.0.0]
Address to bind to
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
