.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-migrate-nodes 1  "nodes " 
.SH NAME
manta\-migrate\-nodes \- Move nodes between clusters
.SH SYNOPSIS
\fBmanta migrate nodes\fR [\fB\-f\fR|\fB\-\-from\fR] <\fB\-t\fR|\fB\-\-to\fR> [\fB\-d\fR|\fB\-\-dry\-run\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIXNAMES\fR> 
.SH DESCRIPTION
Move nodes between clusters
.SH OPTIONS
.TP
\fB\-f\fR, \fB\-\-from\fR \fI<NAME>\fR
Source cluster to move nodes from
.TP
\fB\-t\fR, \fB\-\-to\fR \fI<NAME>\fR
Destination cluster to move nodes to
.TP
\fB\-d\fR, \fB\-\-dry\-run\fR
Simulate the operation without making changes
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<FORMAT>\fR [default: table]
Output format
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
table
.IP \(bu 2
json
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIXNAMES\fR>
Xnames, NIDs, or a hostlist expression.
eg: \*(Aqx1003c1s7b0n0,x1003c1s7b0n1\*(Aq
