.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-delete-redfish-endpoints 1  "redfish-endpoints " 
.SH NAME
manta\-delete\-redfish\-endpoints \- Delete a Redfish endpoint
.SH SYNOPSIS
\fBmanta delete redfish\-endpoints\fR <\fB\-i\fR|\fB\-\-id\fR> [\fB\-o\fR|\fB\-\-output\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Delete a Redfish endpoint
.SH OPTIONS
.TP
\fB\-i\fR, \fB\-\-id\fR \fI<XNAME>\fR
Xname of the Redfish endpoint to delete
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<FORMAT>\fR [default: table]
Output format
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
table
.IP \(bu 2
json
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
