.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-get-templates 1  "templates " 
.SH NAME
manta\-get\-templates \- List BOS session templates (filter by name, group, or recency)
.SH SYNOPSIS
\fBmanta get templates\fR [\fB\-n\fR|\fB\-\-name\fR] [\fB\-m\fR|\fB\-\-most\-recent\fR] [\fB\-l\fR|\fB\-\-limit\fR] [\fB\-H\fR|\fB\-\-group\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List BOS session templates (filter by name, group, or recency)
.SH OPTIONS
.TP
\fB\-n\fR, \fB\-\-name\fR \fI<NAME>\fR
Show only the template with this exact name
.TP
\fB\-m\fR, \fB\-\-most\-recent\fR
Return only the most recent (equivalent to \-\-limit 1)
.TP
\fB\-l\fR, \fB\-\-limit\fR \fI<VALUE>\fR
Return only the <VALUE> most recent templates
.TP
\fB\-H\fR, \fB\-\-group\fR \fI<GROUP_NAME>\fR
Show only templates whose boot sets target this group
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<FORMAT>\fR [default: table]
Output format
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
json
.IP \(bu 2
table
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
