.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-power-on-nodes 1  "nodes " 
.SH NAME
manta\-power\-on\-nodes \- Power on a set of nodes
.SH SYNOPSIS
\fBmanta power on nodes\fR [\fB\-y\fR|\fB\-\-assume\-yes\fR] [\fB\-\-no\-wait\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINODES\fR> 
.SH DESCRIPTION
Power on a set of nodes
.SH OPTIONS
.TP
\fB\-y\fR, \fB\-\-assume\-yes\fR
Skip confirmation prompts
.TP
\fB\-\-no\-wait\fR
Return as soon as the transition is queued; don\*(Aqt poll for completion
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<FORMAT>\fR [default: table]
Output format
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
table
.IP \(bu 2
json
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINODES\fR>
Xnames, NIDs, or a hostlist expression.
eg: \*(Aqx1003c1s7b0n0,x1003c1s7b0n1\*(Aq, \*(Aqnid001313,nid001314\*(Aq,
\*(Aqx1003c1s7b0n[0\-1],x1003c1s7b1n0\*(Aq, \*(Aqnid00131[0\-9]\*(Aq
