.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-apply-boot 1  "boot " 
.SH NAME
manta\-apply\-boot \- Update boot parameters and runtime configuration
.SH SYNOPSIS
\fBmanta apply boot\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Update boot parameters and runtime configuration
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
manta\-apply\-boot\-nodes(1)
Update boot parameters for a set of nodes
.TP
manta\-apply\-boot\-group(1)
Update boot parameters for all nodes in a group
.TP
manta\-apply\-boot\-cluster(1)
[DEPRECATED] Use \*(Aqmanta apply boot group\*(Aq instead
