.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-restore 1  "restore " 
.SH NAME
manta\-restore \- Restore a virtual cluster from a backup bundle
.SH SYNOPSIS
\fBmanta restore\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Restore a virtual cluster from a backup bundle
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
manta\-restore\-vcluster(1)
Restore a virtual cluster from a backup bundle
