.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-backup-vcluster 1  "vcluster " 
.SH NAME
manta\-backup\-vcluster \- Back up a virtual cluster (images, boot settings, group membership)
.SH SYNOPSIS
\fBmanta backup vcluster\fR [\fB\-b\fR|\fB\-\-bos\fR] [\fB\-d\fR|\fB\-\-destination\fR] [\fB\-p\fR|\fB\-\-pre\-hook\fR] [\fB\-a\fR|\fB\-\-post\-hook\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Back up a virtual cluster\*(Aqs configuration: images, boot settings, and group membership.
.PP
The backup is derived from the specified session template.
.SH OPTIONS
.TP
\fB\-b\fR, \fB\-\-bos\fR \fI<SESSIONTEMPLATE>\fR
Session template to derive the backup from
.TP
\fB\-d\fR, \fB\-\-destination\fR \fI<FOLDER>\fR
Destination directory for the backup files
.TP
\fB\-p\fR, \fB\-\-pre\-hook\fR \fI<SCRIPT>\fR
Command to run before the backup.
eg: \-\-pre\-hook "echo hello"
.TP
\fB\-a\fR, \fB\-\-post\-hook\fR \fI<SCRIPT>\fR
Command to run after a successful backup.
eg: \-\-post\-hook "echo hello"
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<FORMAT>\fR [default: table]
Output format
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
table
.IP \(bu 2
json
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
