.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-config-set-hsm 1  "hsm " 
.SH NAME
manta\-config\-set\-hsm \- Set the active node group
.SH SYNOPSIS
\fBmanta config set hsm\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIGROUP_NAME\fR> 
.SH DESCRIPTION
Set the active node group
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIGROUP_NAME\fR>
Node group name
