.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-apply-hardware-cluster 1  "cluster " 
.SH NAME
manta\-apply\-hardware\-cluster \- [DEPRECATED] Use \*(Aqmanta apply hardware group\*(Aq instead
.SH SYNOPSIS
\fBmanta apply hardware cluster\fR <\fB\-P\fR|\fB\-\-pattern\fR> <\fB\-t\fR|\fB\-\-target\-group\fR> <\fB\-p\fR|\fB\-\-parent\-group\fR> [\fB\-d\fR|\fB\-\-dry\-run\fR] [\fB\-c\fR|\fB\-\-create\-target\-group\fR] [\fB\-D\fR|\fB\-\-delete\-empty\-parent\-group\fR] [\fB\-u\fR|\fB\-\-unpin\-nodes\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
[DEPRECATED] Use \*(Aqmanta apply hardware group\*(Aq instead
.SH OPTIONS
.TP
\fB\-P\fR, \fB\-\-pattern\fR \fI<PATTERN>\fR
Hardware pattern: <component>:<qty>[:<component>:<qty>...].
eg: \*(Aqa100:12:epyc:5\*(Aq
.TP
\fB\-t\fR, \fB\-\-target\-group\fR \fI<TARGET_GROUP_NAME>\fR
Group to rescale
.TP
\fB\-p\fR, \fB\-\-parent\-group\fR \fI<PARENT_GROUP_NAME>\fR
Group that donates or receives the redistributed nodes
.TP
\fB\-d\fR, \fB\-\-dry\-run\fR
Simulate the operation without making changes
.TP
\fB\-c\fR, \fB\-\-create\-target\-group\fR
Create the target group if it does not exist
.TP
\fB\-D\fR, \fB\-\-delete\-empty\-parent\-group\fR
Delete the parent group if empty after this operation
.TP
\fB\-u\fR, \fB\-\-unpin\-nodes\fR
Allow any available nodes to be selected
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<FORMAT>\fR [default: table]
Output format
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
table
.IP \(bu 2
json
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
