.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-apply-hardware 1  "hardware " 
.SH NAME
manta\-apply\-hardware \- [experimental] Rescale a group\*(Aqs hardware allocation
.SH SYNOPSIS
\fBmanta apply hardware\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
[experimental] Rescale a group\*(Aqs hardware allocation
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
manta\-apply\-hardware\-group(1)
[experimental] Rescale a group\*(Aqs hardware allocation
