.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-cli-config-unset-hsm 1  "hsm " 
.SH NAME
manta\-cli\-config\-unset\-hsm \- Clear the active node group
.SH SYNOPSIS
\fBmanta\-cli config unset hsm\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Clear the active node group
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
