.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-add-node 1  "node " 
.SH NAME
manta\-add\-node \- Register a new node in the hardware state manager
.SH SYNOPSIS
\fBmanta add node\fR <\fB\-i\fR|\fB\-\-id\fR> <\fB\-g\fR|\fB\-\-group\fR> [\fB\-H\fR|\fB\-\-hardware\fR] [\fB\-a\fR|\fB\-\-arch\fR] [\fB\-d\fR|\fB\-\-disabled\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Register a new node in the hardware state manager.
.PP
Use this for nodes that don\*(Aqt exist yet. To attach existing nodes to a group, use `manta add nodes` (plural).
.SH OPTIONS
.TP
\fB\-i\fR, \fB\-\-id\fR \fI<XNAME>\fR
Xname to register
.TP
\fB\-g\fR, \fB\-\-group\fR \fI<NAME>\fR
Group to put the new node into
.TP
\fB\-H\fR, \fB\-\-hardware\fR \fI<FILE>\fR
File containing hardware information
.TP
\fB\-a\fR, \fB\-\-arch\fR \fI<VALUE>\fR
Node architecture
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
X86
.IP \(bu 2
ARM
.IP \(bu 2
Other
.RE
.TP
\fB\-d\fR, \fB\-\-disabled\fR
Register the node as disabled
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<FORMAT>\fR [default: table]
Output format
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
table
.IP \(bu 2
json
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
