.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-migrate-vCluster 1  "vCluster " 
.SH NAME
manta\-migrate\-vCluster \- [experimental] Migrate a cluster
.SH SYNOPSIS
\fBmanta migrate vCluster\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
[experimental] Migrate a cluster
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
manta\-migrate\-vCluster\-backup(1)
[DEPRECATED] Use \*(Aqmanta backup vcluster\*(Aq instead
.TP
manta\-migrate\-vCluster\-restore(1)
[DEPRECATED] Use \*(Aqmanta restore vcluster\*(Aq instead. The old path keeps working for one release.
