.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-get-hardware 1  "hardware " 
.SH NAME
manta\-get\-hardware \- Inspect hardware components
.SH SYNOPSIS
\fBmanta get hardware\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Inspect hardware components
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
manta\-get\-hardware\-cluster(1)
[DEPRECATED] Use \*(Aqmanta get group\-hardware\*(Aq instead
.TP
manta\-get\-hardware\-nodes(1)
Show hardware inventory for a set of nodes
