.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-migrate-vCluster-restore 1  "restore " 
.SH NAME
manta\-migrate\-vCluster\-restore \- Restore a cluster from a backup
.SH SYNOPSIS
\fBmanta migrate vCluster restore\fR [\fB\-b\fR|\fB\-\-bos\-file\fR] [\fB\-c\fR|\fB\-\-cfs\-file\fR] [\fB\-j\fR|\fB\-\-hsm\-file\fR] [\fB\-m\fR|\fB\-\-ims\-file\fR] [\fB\-i\fR|\fB\-\-image\-dir\fR] [\fB\-p\fR|\fB\-\-pre\-hook\fR] [\fB\-a\fR|\fB\-\-post\-hook\fR] [\fB\-o\fR|\fB\-\-overwrite\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Restore a cluster from a backup
.SH OPTIONS
.TP
\fB\-b\fR, \fB\-\-bos\-file\fR \fI<FILE>\fR
Session template backup file
.TP
\fB\-c\fR, \fB\-\-cfs\-file\fR \fI<FILE>\fR
Configuration backup file
.TP
\fB\-j\fR, \fB\-\-hsm\-file\fR \fI<FILE>\fR
Group description backup file
.TP
\fB\-m\fR, \fB\-\-ims\-file\fR \fI<FILE>\fR
Image metadata backup file
.TP
\fB\-i\fR, \fB\-\-image\-dir\fR \fI<PATH>\fR
Directory containing the image files
.TP
\fB\-p\fR, \fB\-\-pre\-hook\fR \fI<SCRIPT>\fR
Command to run before the restore.
eg: \-\-pre\-hook "echo hello"
.TP
\fB\-a\fR, \fB\-\-post\-hook\fR \fI<SCRIPT>\fR
Command to run after a successful restore.
eg: \-\-post\-hook "echo hello"
.TP
\fB\-o\fR, \fB\-\-overwrite\fR
Overwrite existing data
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
