.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-cli-config-set-site 1  "site " 
.SH NAME
manta\-cli\-config\-set\-site \- Set the active site
.SH SYNOPSIS
\fBmanta\-cli config set site\fR [\fB\-h\fR|\fB\-\-help\fR] <\fISITE_NAME\fR> 
.SH DESCRIPTION
Set the active site
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISITE_NAME\fR>
Site name
