.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-get-sessions 1  "sessions " 
.SH NAME
manta\-get\-sessions \- List configuration sessions
.SH SYNOPSIS
\fBmanta get sessions\fR [\fB\-n\fR|\fB\-\-name\fR] [\fB\-a\fR|\fB\-\-min\-age\fR] [\fB\-A\fR|\fB\-\-max\-age\fR] [\fB\-t\fR|\fB\-\-type\fR] [\fB\-s\fR|\fB\-\-status\fR] [\fB\-m\fR|\fB\-\-most\-recent\fR] [\fB\-l\fR|\fB\-\-limit\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-x\fR|\fB\-\-xnames\fR] [\fB\-H\fR|\fB\-\-group\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List configuration sessions
.SH OPTIONS
.TP
\fB\-n\fR, \fB\-\-name\fR \fI<SESSION_NAME>\fR
Return only the session with this name
.TP
\fB\-a\fR, \fB\-\-min\-age\fR \fI<VALUE>\fR
Return only sessions older than this age (eg: \*(Aq1d\*(Aq, \*(Aq6h\*(Aq)
.TP
\fB\-A\fR, \fB\-\-max\-age\fR \fI<VALUE>\fR
Return only sessions younger than this age (eg: \*(Aq1d\*(Aq, \*(Aq6h\*(Aq)
.TP
\fB\-t\fR, \fB\-\-type\fR \fI<VALUE>\fR
Return only sessions of this type
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
image
.IP \(bu 2
runtime
.RE
.TP
\fB\-s\fR, \fB\-\-status\fR \fI<VALUE>\fR
Return only sessions with this status
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
pending
.IP \(bu 2
running
.IP \(bu 2
complete
.RE
.TP
\fB\-m\fR, \fB\-\-most\-recent\fR
Return only the most recent session (equivalent to \-\-limit 1)
.TP
\fB\-l\fR, \fB\-\-limit\fR \fI<VALUE>\fR
Return only the <VALUE> most recent sessions
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<FORMAT>\fR
Output format
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
json
.RE
.TP
\fB\-x\fR, \fB\-\-xnames\fR \fI<NODES>\fR
Xnames, NIDs, or hostlist expression. Returns sessions targeting these nodes or their groups
.TP
\fB\-H\fR, \fB\-\-group\fR \fI<GROUP_NAME>\fR
Node group name. Returns sessions targeting this group or its members
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
