.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-console 1  "console " 
.SH NAME
manta\-console \- Open an interactive console to a node or configuration session
.SH SYNOPSIS
\fBmanta console\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Open an interactive console to a node or configuration session
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
manta\-console\-node(1)
Connect to a node\*(Aqs serial console
.TP
manta\-console\-target\-ansible(1)
Connect to the Ansible target container of a configuration session
