.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-cli-update 1  "update " 
.SH NAME
manta\-cli\-update \- Update system resources
.SH SYNOPSIS
\fBmanta\-cli update\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Update system resources
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
manta\-cli\-update\-boot\-parameters(1)
Update boot parameters for nodes
.TP
manta\-cli\-update\-redfish\-endpoint(1)
Update a Redfish endpoint
