.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-apply-boot-nodes 1  "nodes " 
.SH NAME
manta\-apply\-boot\-nodes \- Update boot parameters for a set of nodes
.SH SYNOPSIS
\fBmanta apply boot nodes\fR [\fB\-i\fR|\fB\-\-boot\-image\fR] [\fB\-b\fR|\fB\-\-boot\-image\-configuration\fR] [\fB\-r\fR|\fB\-\-runtime\-configuration\fR] [\fB\-k\fR|\fB\-\-kernel\-parameters\fR] [\fB\-y\fR|\fB\-\-assume\-yes\fR] [\fB\-\-do\-not\-reboot\fR] [\fB\-d\fR|\fB\-\-dry\-run\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINODES\fR> 
.SH DESCRIPTION
Update the boot parameters (image, runtime configuration, and kernel parameters) for a set of nodes.
.PP
The boot image can be specified by image ID or by the configuration name used to build it (the most recent matching image is used).
.PP
eg:
  manta apply boot nodes \\
    \-\-boot\-image\-configuration <config\-name> \\
    \-\-runtime\-configuration <config\-name> <nodes>
.SH OPTIONS
.TP
\fB\-i\fR, \fB\-\-boot\-image\fR \fI<IMAGE_ID>\fR
Image ID to boot the nodes
.TP
\fB\-b\fR, \fB\-\-boot\-image\-configuration\fR \fI<NAME>\fR
Configuration name used to build the boot image (uses the most recent matching image)
.TP
\fB\-r\fR, \fB\-\-runtime\-configuration\fR \fI<NAME>\fR
Configuration to apply to nodes after booting
.TP
\fB\-k\fR, \fB\-\-kernel\-parameters\fR \fI<VALUE>\fR
Kernel parameters to assign to the nodes
.TP
\fB\-y\fR, \fB\-\-assume\-yes\fR
Skip confirmation prompts
.TP
\fB\-\-do\-not\-reboot\fR
Suppress the automatic reboot after updating boot parameters
.TP
\fB\-d\fR, \fB\-\-dry\-run\fR
Simulate the operation without making changes
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
<\fINODES\fR>
Xnames, NIDs, or a hostlist expression.
eg: \*(Aqx1003c1s7b0n0,x1003c1s7b0n1\*(Aq, \*(Aqnid001313,nid001314\*(Aq,
\*(Aqx1003c1s7b0n[0\-1],x1003c1s7b1n0\*(Aq, \*(Aqnid00131[0\-9]\*(Aq
