.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-cli-config-set-log 1  "log " 
.SH NAME
manta\-cli\-config\-set\-log \- Set the log verbosity level
.SH SYNOPSIS
\fBmanta\-cli config set log\fR [\fB\-h\fR|\fB\-\-help\fR] <\fILOG_LEVEL\fR> 
.SH DESCRIPTION
Set the log verbosity level
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fILOG_LEVEL\fR>
Log verbosity level
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
error
.IP \(bu 2
warn
.IP \(bu 2
info
.IP \(bu 2
debug
.IP \(bu 2
trace
.RE
