.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-cli-apply-hardware 1  "hardware " 
.SH NAME
manta\-cli\-apply\-hardware \- [experimental] Rescale a cluster\*(Aqs hardware allocation
.SH SYNOPSIS
\fBmanta\-cli apply hardware\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
[experimental] Rescale a cluster\*(Aqs hardware allocation
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
manta\-cli\-apply\-hardware\-cluster(1)
[experimental] Rescale a cluster\*(Aqs hardware allocation
