.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-apply-template 1  "template " 
.SH NAME
manta\-apply\-template \- Boot nodes using an existing session template
.SH SYNOPSIS
\fBmanta apply template\fR [\fB\-n\fR|\fB\-\-name\fR] [\fB\-o\fR|\fB\-\-operation\fR] <\fB\-t\fR|\fB\-\-template\fR> <\fB\-l\fR|\fB\-\-limit\fR> [\fB\-i\fR|\fB\-\-include\-disabled\fR] [\fB\-y\fR|\fB\-\-assume\-yes\fR] [\fB\-d\fR|\fB\-\-dry\-run\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Boot nodes using an existing session template
.SH OPTIONS
.TP
\fB\-n\fR, \fB\-\-name\fR \fI<VALUE>\fR
Name of the boot session to create
.TP
\fB\-o\fR, \fB\-\-operation\fR \fI<VALUE>\fR [default: reboot]
Boot operation to perform
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
reboot
.IP \(bu 2
boot
.IP \(bu 2
shutdown
.RE
.TP
\fB\-t\fR, \fB\-\-template\fR \fI<VALUE>\fR
Session template name
.TP
\fB\-l\fR, \fB\-\-limit\fR \fI<VALUE>\fR
Limit to specific nodes, groups, or roles (OR by default; prefix with \*(Aq&\*(Aq for AND or \*(Aq!\*(Aq for NOT)
.TP
\fB\-i\fR, \fB\-\-include\-disabled\fR
Include nodes marked as disabled in the hardware state manager
.TP
\fB\-y\fR, \fB\-\-assume\-yes\fR
Skip confirmation prompts
.TP
\fB\-d\fR, \fB\-\-dry\-run\fR
Simulate the operation without making changes
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
