.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-config-unset-auth 1  "auth " 
.SH NAME
manta\-config\-unset\-auth \- Clear the cached authentication token
.SH SYNOPSIS
\fBmanta config unset auth\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Clear the cached authentication token
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
