.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-cli-power-reset 1  "reset " 
.SH NAME
manta\-cli\-power\-reset \- Reset (reboot) nodes or a cluster
.SH SYNOPSIS
\fBmanta\-cli power reset\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Reset (reboot) nodes or a cluster
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
manta\-cli\-power\-reset\-cluster(1)
Reset all nodes in a cluster
.TP
manta\-cli\-power\-reset\-nodes(1)
Reset a set of nodes
