.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-delete-redfish-endpoint 1  "redfish-endpoint " 
.SH NAME
manta\-delete\-redfish\-endpoint \- Delete a Redfish endpoint
.SH SYNOPSIS
\fBmanta delete redfish\-endpoint\fR <\fB\-i\fR|\fB\-\-id\fR> [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Delete a Redfish endpoint
.SH OPTIONS
.TP
\fB\-i\fR, \fB\-\-id\fR \fI<XNAME>\fR
Xname of the Redfish endpoint to delete
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
