.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-cli-config 1  "config " 
.SH NAME
manta\-cli\-config \- Manage manta CLI configuration
.SH SYNOPSIS
\fBmanta\-cli config\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Manage manta CLI configuration
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
manta\-cli\-config\-show(1)
Show current configuration values
.TP
manta\-cli\-config\-set(1)
Set a configuration value
.TP
manta\-cli\-config\-unset(1)
Clear a configuration value
.TP
manta\-cli\-config\-gen\-autocomplete(1)
Generate shell completion scripts
