.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-apply-session 1  "session " 
.SH NAME
manta\-apply\-session \- Create and run a configuration session from a local repo
.SH SYNOPSIS
\fBmanta apply session\fR <\fB\-n\fR|\fB\-\-name\fR> [\fB\-p\fR|\fB\-\-playbook\-name\fR] <\fB\-r\fR|\fB\-\-repo\-path\fR> [\fB\-w\fR|\fB\-\-watch\-logs\fR] [\fB\-t\fR|\fB\-\-timestamps\fR] [\fB\-v\fR|\fB\-\-ansible\-verbosity\fR] [\fB\-P\fR|\fB\-\-ansible\-passthrough\fR] <\fB\-l\fR|\fB\-\-ansible\-limit\fR> [\fB\-H\fR|\fB\-\-hsm\-group\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Create and run a configuration session from a local git repo.
.PP
The repo must already exist in the system\*(Aqs VCS. The session runs the specified Ansible playbook against the target nodes or group.
.SH OPTIONS
.TP
\fB\-n\fR, \fB\-\-name\fR \fI<VALUE>\fR
Session name
.TP
\fB\-p\fR, \fB\-\-playbook\-name\fR \fI<VALUE>\fR [default: site.yml]
Ansible playbook filename
.TP
\fB\-r\fR, \fB\-\-repo\-path\fR \fI<REPO_PATH>\fR
Path to the local git repo containing the Ansible playbook
.TP
\fB\-w\fR, \fB\-\-watch\-logs\fR
Stream session logs to stdout
.TP
\fB\-t\fR, \fB\-\-timestamps\fR
Show log timestamps
.TP
\fB\-v\fR, \fB\-\-ansible\-verbosity\fR \fI<VALUE>\fR [default: 2]
Ansible verbosity level (1 = \-v, 2 = \-vv, …, max 4)
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
0
.IP \(bu 2
1
.IP \(bu 2
2
.IP \(bu 2
3
.IP \(bu 2
4
.RE
.TP
\fB\-P\fR, \fB\-\-ansible\-passthrough\fR \fI<VALUE>\fR
Additional Ansible flags (limited to \-\-extra\-vars, \-\-forks, \-\-skip\-tags, \-\-start\-at\-task, \-\-tags)
.TP
\fB\-l\fR, \fB\-\-ansible\-limit\fR \fI<VALUE>\fR
Limit the session to specific nodes (must be a subset of \-\-hsm\-group if both are provided)
.TP
\fB\-H\fR, \fB\-\-hsm\-group\fR \fI<GROUP_NAME>\fR
Node group name
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
