.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-add-hardware 1  "hardware " 
.SH NAME
manta\-add\-hardware \- [experimental] Add hardware components to a cluster
.SH SYNOPSIS
\fBmanta add hardware\fR [\fB\-P\fR|\fB\-\-pattern\fR] [\fB\-t\fR|\fB\-\-target\-cluster\fR] [\fB\-p\fR|\fB\-\-parent\-cluster\fR] [\fB\-d\fR|\fB\-\-dry\-run\fR] [\fB\-c\fR|\fB\-\-create\-hsm\-group\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
[experimental] Add hardware components to a cluster
.SH OPTIONS
.TP
\fB\-P\fR, \fB\-\-pattern\fR \fI<PATTERN>\fR
Hardware component pattern
.TP
\fB\-t\fR, \fB\-\-target\-cluster\fR \fI<NAME>\fR
Cluster to add components to
.TP
\fB\-p\fR, \fB\-\-parent\-cluster\fR \fI<NAME>\fR
Cluster that donates the components
.TP
\fB\-d\fR, \fB\-\-dry\-run\fR
Simulate the operation without making changes
.TP
\fB\-c\fR, \fB\-\-create\-hsm\-group\fR
Create the target cluster if it does not exist
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
