.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-cli-apply-configuration 1  "configuration " 
.SH NAME
manta\-cli\-apply\-configuration \- Create a configuration (deprecated — use \*(Aqapply sat\-file\*(Aq)
.SH SYNOPSIS
\fBmanta\-cli apply configuration\fR <\fB\-t\fR|\fB\-\-sat\-template\-file\fR> [\fB\-f\fR|\fB\-\-values\-file\fR] [\fB\-V\fR|\fB\-\-values\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-H\fR|\fB\-\-hsm\-group\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Create a configuration (deprecated — use \*(Aqapply sat\-file\*(Aq)
.SH OPTIONS
.TP
\fB\-t\fR, \fB\-\-sat\-template\-file\fR \fI<SAT_FILE_PATH>\fR
SAT file path
.TP
\fB\-f\fR, \fB\-\-values\-file\fR \fI<VALUES_FILE_PATH>\fR
Values file for SAT jinja2 templates
.TP
\fB\-V\fR, \fB\-\-values\fR \fI<VALUES>\fR
Inline values for SAT jinja2 templates (overrides \-\-values\-file)
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<FORMAT>\fR
Output format
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
json
.RE
.TP
\fB\-H\fR, \fB\-\-hsm\-group\fR \fI<GROUP_NAME>\fR
Node group name
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
