.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-cli-config-set 1  "set " 
.SH NAME
manta\-cli\-config\-set \- Set a configuration value
.SH SYNOPSIS
\fBmanta\-cli config set\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Set a configuration value
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
manta\-cli\-config\-set\-hsm(1)
Set the active node group
.TP
manta\-cli\-config\-set\-parent\-hsm(1)
Set the parent node group
.TP
manta\-cli\-config\-set\-site(1)
Set the active site
.TP
manta\-cli\-config\-set\-log(1)
Set the log verbosity level
