.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-console-target-ansible 1  "target-ansible " 
.SH NAME
manta\-console\-target\-ansible \- Connect to the Ansible target container of a configuration session
.SH SYNOPSIS
\fBmanta console target\-ansible\fR [\fB\-h\fR|\fB\-\-help\fR] <\fISESSION_NAME\fR> 
.SH DESCRIPTION
Connect to the Ansible target container of a configuration session
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISESSION_NAME\fR>
Configuration session name
