.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-cli-console-node 1  "node " 
.SH NAME
manta\-cli\-console\-node \- Connect to a node\*(Aqs serial console
.SH SYNOPSIS
\fBmanta\-cli console node\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIXNAME\fR> 
.SH DESCRIPTION
Connect to a node\*(Aqs serial console.
.PP
Accepts an xname or NID.
eg: \*(Aqx1003c1s7b0n0\*(Aq or \*(Aqnid001313\*(Aq
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
<\fIXNAME\fR>
Node xname or NID
