.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-get 1  "get " 
.SH NAME
manta\-get \- Query system resources
.SH SYNOPSIS
\fBmanta get\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Query system resources
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
manta\-get\-groups(1)
List node groups
.TP
manta\-get\-hardware(1)
Inspect hardware components
.TP
manta\-get\-sessions(1)
List configuration sessions
.TP
manta\-get\-configurations(1)
List configurations
.TP
manta\-get\-templates(1)
List session templates
.TP
manta\-get\-cluster(1)
[DEPRECATED] Use \*(Aqmanta get group\-nodes\*(Aq instead
.TP
manta\-get\-group\-nodes(1)
Show node details and status for a group
.TP
manta\-get\-group\-hardware(1)
Show hardware inventory for a group
.TP
manta\-get\-nodes(1)
Show node details and status
.TP
manta\-get\-images(1)
List images
.TP
manta\-get\-boot\-parameters(1)
Show boot parameters for nodes or a group
.TP
manta\-get\-kernel\-parameters(1)
Show kernel parameters for nodes or a group
.TP
manta\-get\-redfish\-endpoints(1)
List Redfish endpoints
