.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-add 1  "add " 
.SH NAME
manta\-add \- Register new nodes, groups, boot/kernel parameters, hardware components, or Redfish endpoints
.SH SYNOPSIS
\fBmanta add\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Register new nodes, groups, boot/kernel parameters, hardware components, or Redfish endpoints
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
manta\-add\-node(1)
Register a new node in the hardware state manager
.TP
manta\-add\-nodes(1)
Add existing nodes to a group
.TP
manta\-add\-group(1)
Create a node group
.TP
manta\-add\-hardware(1)
[experimental] Add hardware components to a group
.TP
manta\-add\-boot\-parameters(1)
Create a BSS boot\-parameters entry (kernel, initrd, params, cloud\-init) for one or more nodes
.TP
manta\-add\-kernel\-parameters(1)
Append kernel parameters to nodes (leaves existing parameters untouched unless \-\-overwrite is set)
.TP
manta\-add\-redfish\-endpoints(1)
Register a new Redfish endpoint
