.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-config-show 1  "show " 
.SH NAME
manta\-config\-show \- Show current configuration values
.SH SYNOPSIS
\fBmanta config show\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show current configuration values
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
