.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-apply-ephemeral-environment 1  "ephemeral-environment " 
.SH NAME
manta\-apply\-ephemeral\-environment \- Launch an ephemeral SSH environment from an image
.SH SYNOPSIS
\fBmanta apply ephemeral\-environment\fR <\fB\-i\fR|\fB\-\-image\-id\fR> [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Launch an ephemeral SSH environment from an image.
.PP
Returns an SSH hostname once the environment is ready (usually within a few seconds).
.SH OPTIONS
.TP
\fB\-i\fR, \fB\-\-image\-id\fR \fI<IMAGE_ID>\fR
Image ID to use
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
