.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-config-unset-parent-hsm 1  "parent-hsm " 
.SH NAME
manta\-config\-unset\-parent\-hsm \- Clear the parent node group
.SH SYNOPSIS
\fBmanta config unset parent\-hsm\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Clear the parent node group
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
