.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta 1  "manta 2.0.0-beta.7" 
.SH NAME
manta
.SH SYNOPSIS
\fBmanta\fR [\fB\-\-site\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-\-site\fR \fI<SITE_NAME>\fR
Override the active site for this invocation
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
manta\-config(1)
Manage manta CLI configuration
.TP
manta\-get(1)
Query system resources
.TP
manta\-add(1)
Create system resources
.TP
manta\-update(1)
Update system resources
.TP
manta\-apply(1)
Apply changes to the system
.TP
manta\-delete(1)
Delete system resources
.TP
manta\-migrate(1)
Move nodes or clusters between groups
.TP
manta\-power(1)
Manage node and cluster power state
.TP
manta\-log(1)
Stream configuration session logs
.TP
manta\-console(1)
Open an interactive console to a node or configuration session
.TP
manta\-add\-nodes\-to\-groups(1)
Add nodes to one or more groups
.TP
manta\-remove\-nodes\-from\-groups(1)
Remove nodes from one or more groups
.SH VERSION
v2.0.0\-beta.7
