.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-delete-boot-parameters 1  "boot-parameters " 
.SH NAME
manta\-delete\-boot\-parameters \- Delete boot parameters for nodes
.SH SYNOPSIS
\fBmanta delete boot\-parameters\fR [\fB\-H\fR|\fB\-\-hosts\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Delete boot parameters for nodes
.SH OPTIONS
.TP
\fB\-H\fR, \fB\-\-hosts\fR \fI<XNAMES>\fR
Xnames of the nodes
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
