.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manta-apply-boot-group 1  "group " 
.SH NAME
manta\-apply\-boot\-group \- Update boot parameters for all nodes in a group
.SH SYNOPSIS
\fBmanta apply boot group\fR [\fB\-i\fR|\fB\-\-boot\-image\fR] [\fB\-b\fR|\fB\-\-boot\-image\-configuration\fR] [\fB\-r\fR|\fB\-\-runtime\-configuration\fR] [\fB\-k\fR|\fB\-\-kernel\-parameters\fR] [\fB\-y\fR|\fB\-\-assume\-yes\fR] [\fB\-\-do\-not\-reboot\fR] [\fB\-d\fR|\fB\-\-dry\-run\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fICLUSTER_NAME\fR> 
.SH DESCRIPTION
Update the boot parameters (image, runtime configuration, and kernel parameters) for all nodes in a group.
.PP
The boot image can be specified by image ID or by the configuration name used to build it (the most recent matching image is used).
.PP
eg:
  manta apply boot group \\
    \-\-boot\-image\-configuration <config\-name> \\
    \-\-runtime\-configuration <config\-name> <group\-name>
.SH OPTIONS
.TP
\fB\-i\fR, \fB\-\-boot\-image\fR \fI<IMAGE_ID>\fR
Image ID to boot the nodes
.TP
\fB\-b\fR, \fB\-\-boot\-image\-configuration\fR \fI<NAME>\fR
Configuration name used to build the boot image (uses the most recent matching image)
.TP
\fB\-r\fR, \fB\-\-runtime\-configuration\fR \fI<NAME>\fR
Configuration to apply to nodes after booting
.TP
\fB\-k\fR, \fB\-\-kernel\-parameters\fR \fI<VALUE>\fR
Kernel parameters to assign to all group members
.TP
\fB\-y\fR, \fB\-\-assume\-yes\fR
Skip confirmation prompts
.TP
\fB\-\-do\-not\-reboot\fR
Suppress the automatic reboot after updating boot parameters
.TP
\fB\-d\fR, \fB\-\-dry\-run\fR
Simulate the operation without making changes
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<FORMAT>\fR [default: table]
Output format
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
table
.IP \(bu 2
json
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
<\fICLUSTER_NAME\fR>
Group name
